version: '3.7'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app/src
    ports:
      - 8080:8080
    environment:
      - TOKEN=${TOKEN}